const user = {
    name: 'True_Root_Support',
    definition: `create table public."True_Root_Support" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    email character varying not null,
    message character varying not null,
    response character varying null,
    constraint True_Root_Support_pkey primary key (id)
  ) tablespace pg_default;`
};

export default user;
