import "@/style/globals.css";
import lufga from "@/app/lufga";
import Header from "@/components/layout/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${lufga.className} antialiased selection:bg-primary selection:text-white`}>
    <div className="page-wraper">
        <Header />
        <div className="page-content bg-light overflow-hidden">
            {children}
        </div>
    </div>
    </body>
    </html>
);
}
